spring:
  datasource:
    url: jdbc:mysql://mysql-0.mysql:3306/product?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: product
    password: product1234