spring:
  datasource:
    url: jdbc:mysql://mysql-0.mysql:3306/supplier?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: supplier
    password: supplier1234